version: "3"

services:
  api:
    build: ./api
    image: api_image:v1
    container_name: api_container
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app_jedy:delegated
      - /app_jedy/node_modules
    networks:
      app-network:
        ipv4_address: 172.19.0.10 # Connects `api` to the custom network but we assigned an ip address

  myblog:
    build: ./myblog
    image: myblog_image:v1
    container_name: myblog_container
    ports:
      - "3000:3000"
    volumes:
      - ./myblog:/app_jedy
      - /app_jedy/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network # Connects `myblog` to the custom network

# Define the custom network
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
